#+INCLUDE: ../serei-template.org
#+TITLE: Apuntes Segundo Trimestre - SEREI
#+STARTUP: overview

\blankpage

* FTP (/File Transfer protocol/)
*** =ftpd=
**** Instalación
- =sudo apt-get install ftpd=
**** Conexiones

Nos podremos conectar de manera local ejecutando
- =ftp localhost=
Nos pedirá un usuario y una contraseña, estos tienen que ser del sistema, es decir, usar un usuario del sistema con la
contraseña del mismo.

También nos podremos conectar a otro servidor FTP ejecutando
- =ftp NOMBREMAQUINASERVIDOR=
- =ftp IPMAQUINASERVIDOR=
Y al igual que de manera local se nos pedira un usuario y una contraseña existente en la máquina a la que nos conectamos.
**** Usuarios /anonymous/ y ftp

Para hacer /login/ con el usuario /anonymous/ lo que tendremos que hacer es iniciar una conexión FTP normal pero a la hora
en la que se nos pida que introduzcamos el nombre de usuario con el que nos queremos conectar lo que tendremos que hacer será
introducir /anonymous/

Al principio no deberíamos poder conectarnos con ninguno de los dos usuarios, para poder realizar la conexión lo que tendremos que
hacer será crear ambos usuarios en el sistema operativo ejecutando los siguientes comandos
- =sudo adduser ftp=
- =sudo adduser anonymous=
En ambos usuarios pondremos como contraseña el mismo nombre del usuarios, esto no nos afectará en términos de seguridad debido a que
es una contraseña que solo va a ver el sistema operativo, cuando realicemos conexiones FTP a estos usuarios, si queremos introducir la
contraseña establecida no nos dejará conectarnos.

Por último, para poder conectarnos con los usuarios /anonymous/ o ftp lo último que tendremos que hacer será modificar el fichero =/etc/ftpusers= de
tal manera que nos quede de la siguiente manera
#+ATTR_LATEX: :options frame=single
#+BEGIN_SRC bash
  # /etc/ftpusers: list of users disallowed ftp access. See ftpusers(5).

  root
  #ftp
  #anonymous
#+END_SRC

Luego de haber realizado los pasos anteriores ya podremos hacer /login/ con los usuarios
- /anonymous/
  - =ftp localhost || NOMBREMAQUINASERVIDOR || DIRECCIONMAQUINASERVIDOR=
    - */user/*: anonymous
    - */password/*: algo
- ftp
    - */user/*: ftp
    - */password/*: algo

*Estos usuarios tienen muchas restricciones ya que por defecto están enjaulados*
**** Jaulas

El fichero correspondiente a los enjaulamientos en FTP es =/etc/ftpchroot=

Para enjaular a un usuario lo único que tendremos que hacer será añadir el nombre de este usuario al fichero =/etc/ftpchroot=
#+ATTR_LATEX: :options frame=single
#+BEGIN_SRC bash
  # /etc/ftpchroot: list of users who needs to be chrooted. See ftpchroot(5).
  usuario4
#+END_SRC
**** Parar y arrancar el servicio

FTP depende del superdemonio =inetd=. Para parar o arrancar el servicio FTP tendremos que parar o arrancar =inetd=.
#+ATTR_LATEX: :options frame=single
#+BEGIN_SRC bash
  maka@ubuntu101:~$ ps aux | grep -i inetd
  root      9032  0.0  0.0  10696   728 ?        Ss   07:10   0:00 /usr/sbin/inetd
  maka     10499  0.0  0.0  15960   928 pts/1    S+   08:34   0:00 grep --color=auto -i inetd
  maka@ubuntu101:~$ sudo kill 9032
#+END_SRC

Para arrancar el superdemonio lo único que habrá que hacer será ejecutar el comando =intetd=

Para modificar algo del superdemonio =inetd= lo que habría que hacer sería modificar el fichero =/etc/inetd.conf=.

=intetd= también es el superdemonio que maneja a =telnet=. El proceso de arranque y parada de =telnet= es igual que el de FTP.
**** Macros
Para crear macros usáremos
- =$=.
- Se tendrá que crear el fichero =.netrc= en el =$HOME= del usuarios al que queramos automatizar con la macro
#+ATTR_LATEX: :options frame=single
#+BEGIN_SRC bash

  machine 172.26.0.100 login ana password ana	

  macdef macrocasaManuel
  prompt
  cd casaManuel
  cd banio
  !mkdir copiaManuel
  lcd copiaManuel
  !mkdir banio
  lcd banio
  mget *
  cd ..
  lcd ..
  !mkdir cocina
  lcd cocina
  cd cocina
  mget *
  lcd ..
  !mkdir salon
  lcd salon
  cd ..
  cd salon
  mget *
  cd ..
  cd ..
  lcd ..
  lcd ..

  macdef macrocasaAlvaroS
  cd casaAlvaroS
  cd banio
  !mkdir copiaAlvaroS
  lcd copiaAlvaroS
  !mkdir banio
  lcd banio
  mget *
  lcd ..
  cd ..
  !mkdir salon
  lcd salon
  cd salon
  mget *
  lcd ..
  cd ..
  !mkdir cocina
  lcd cocina
  cd cocina
  mget *
  cd ..
  cd ..
  lcd ..
  lcd ..

  macdef macrocasasMA
  $macro macrocasaManuel 
  $macro macrocasaAlvaroS


#+END_SRC

*¡OJO!, es muy importante para que funcione dejar los dos espacios en blanco al final del documento*

**** TODO Automatización
*** =lftp=
**** Instalación
- Recordemos que es un *cliente*
- =sudo apt-get install lftp=
- Este cliente nos ayudará con la transferencia de directorios completos
  
**** Parámetros y uso
- Para mirar la ayuda usaremos ?
- Los parámetros más interesantes son:
  - */mirror/*: copiar un directorio entero
    - =mirror casaMaka=
  - =open=: sirve para conectarse
    - =open 172.26.0.100=
    - *¡OJO!, no usar el usuario =root= para hacer un =open=*
  - =user=: sirve para usar algún usuario
    - =user ana=
- El fichero =.netrc= que hayamos configurado previamente se mantiene con =lftp= 
- Podremos tener algo parecido a las macros con =lftp=
  - Crear un fichero =touch macro=
  - Editar el ficher =vi macro=
#+ATTR_LATEX: :options frame=single
    #+BEGIN_SRC bash

# No hay que dejar un hueco en ana y ana. Es decir, no puede ser ana, ana
      open 172.26.0.100 -u ana,ana
      mirror casaMaka

      
#+END_SRC
   - Ejecutar =lftp -f macro=
- Podremos realizar un /script/
  - Crear el fichero =touch macro2.sh=
  - Editar el /script/ =vi macro2.sh=
#+ATTR_LATEX: :options frame=single
#+BEGIN_SRC bash
  #!/bin/bash
# Este script sube casaMaka de local al 172.26.0.100 con el nombre casaMakita
  lftp 172.26.0.100 -u ana,ana<<EOF
  mirror -R casaMaka casaMakita
  EOF
#+END_SRC 

*** =vsftpd=
- Hasta este punto todo lo que hemos realizado con FTP iba sobre texto plano, a partir de aquí es cuando "meteremos seguridad"
  con temas de cifrado, etc
- Es un *servidor*
**** Instalación
- No se puede instalar junto a =lftp= debido a que chocan o se intentan sobreponer
- =sudo apt-get install vsftpd=
**** Inicio y Parada
- Esta vinculado a =inetd=
- =service status vsftpd=
- =service stop vsftpd=
- =service start vsftpd=
**** Datos "curiosos"
- No tiene macros
**** Securización
1. Uso de certificados.
   - Acceder al fichero =/etc/vsftpd.conf= 
   - Habilitar =ssl_enable = yes=
   - Descomentar nuestros certificados
   - *Generar un certificado SSL*
     - =openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout /etc/ssl/private/vsftpd.key -out /etc/ssl/certs/vsftpd.pem=
#+ATTR_LATEX: :options frame=single
#+BEGIN_SRC bash
	 Generating a 1024 bit RSA private key
	 .++++++
	 ç..............++++++
	 writing new private key to '/etc/ssl/private/vsftpd.key'
	 -----
	 You are about to be asked to enter information that will be incorporated
	 into your certificate request.
	 What you are about to enter is what is called a Distinguished Name or a DN.
	 There are quite a few fields but you can leave some blank
	 For some fields there will be a default value,
	 If you enter '.', the field will be left blank.
	 -----
	 Country Name (2 letter code) [AU]:ES
	 string is too long, it needs to be less than  2 bytes long
	 Country Name (2 letter code) [AU]:ES
	 State or Province Name (full name) [Some-State]:Madrid
	 Locality Name (eg, city) []:Alcala de Henares
	 Organization Name (eg, company) [Internet Widgits Pty Ltd]:IES Alonso de Avellaneda
	 Organizational Unit Name (eg, section) []:ASIR
	 Common Name (e.g. server FQDN or YOUR name) []:ubuntua37pc01.asir2.com
	 Email Address []:ismael.macareno@educa.madrid.org
#+END_SRC

Si miramos en =/etc/ssl/certs/vsftpd.pem= apreciaremos que tenemos lo siguiente
#+ATTR_LATEX: :options frame=single
#+BEGIN_SRC bash
  -----BEGIN CERTIFICATE-----
  MIIDTjCCAregAwIBAgIJALbn6dKu7CogMA0GCSqGSIb3DQEBCwUAMIG/MQswCQYD
  VQQGEwJFUzEPMA0GA1UECAwGTWFkcmlkMRowGAYDVQQHDBFBbGNhbGEgZGUgSGVu
  YXJlczEhMB8GA1UECgwYSUVTIEFsb25zbyBkZSBBdmVsbGFuZWRhMQ0wCwYDVQQL
  DARBU0lSMSAwHgYDVQQDDBd1YnVudHVhMzdwYzAxLmFzaXIyLmNvbTEvMC0GCSqG
  SIb3DQEJARYgaXNtYWVsLm1hY2FyZW5vQGVkdWNhLm1hZHJpZC5vcmcwHhcNMjQx
  MjA5MDgzMTAwWhcNMjUxMjA5MDgzMTAwWjCBvzELMAkGA1UEBhMCRVMxDzANBgNV
  BAgMBk1hZHJpZDEaMBgGA1UEBwwRQWxjYWxhIGRlIEhlbmFyZXMxITAfBgNVBAoM
  GElFUyBBbG9uc28gZGUgQXZlbGxhbmVkYTENMAsGA1UECwwEQVNJUjEgMB4GA1UE
  AwwXdWJ1bnR1YTM3cGMwMS5hc2lyMi5jb20xLzAtBgkqhkiG9w0BCQEWIGlzbWFl
  bC5tYWNhcmVub0BlZHVjYS5tYWRyaWQub3JnMIGfMA0GCSqGSIb3DQEBAQUAA4GN
  ADCBiQKBgQDL4z7yLbMrEfQqlQ1fqj1YU9oMdDZ+73UDkxGLaT//D9M2n9chWDnN
  XypC9kcNbK2yO8BZ6iJApbe6bNMjmdSqT4X5soj/PRkCisUMeBpr7/DFbLL43d3K
  rAj24bA9quPb9qxilYd28aUpYnvYsE3W6l2WQCLsqcvui5dH0DFUGQIDAQABo1Aw
  TjAdBgNVHQ4EFgQUkoNK657t/79lSDwv8Lv5Uk3hYlgwHwYDVR0jBBgwFoAUkoNK
  657t/79lSDwv8Lv5Uk3hYlgwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOB
  gQAabsW3W5XIBfAMfuNKRlD58dc9akSH7u5j7yM5eNzPfGBBYR3Y/5+dKZgdE1Zn
  +kK2tFvKoiv4szuyL5DHowE/f3NmA/ytrGnq8RWTCBcRBcfMkiOiORbKiL0riBO9
  Q0WWlQAKRduM/F2bIdpZnCltr9Y5mN10jY69fDhqHVDcew==
  -----END CERTIFICATE-----
#+END_SRC

Que es nuestra clave *pública*

Luego lo que haremos será hacer un =scp= y llevarnos la clave pública a donde nos interese.
- =sudo scp maka@ubuntu151.local:/etc/ssl/certs/vsftpd.pem /usr/local/share/ca-certificates/vsftpd.crt=

Para "montar" en la otra máquina el certificado deberíamos ejecutar el siguiente comando:
- =openssl x509 -in vsftpd.crt -nout -subject=



